Adding svnlite mode; Adding 2 svn sources

diff --git a/portshaker.subr.in b/portshaker.subr.in
--- a/portshaker.subr.in
+++ b/portshaker.subr.in
@@ -33,6 +33,8 @@ RSYNC=${RSYNC:=rsync}
 RSYNC_FLAGS=""
 SVN="${SVN:=svn}"
 #SVN_FLAGS=""
+SVNLITE="${SVNLITE:svnlite}"
+#SVNLITE_FLAGS=""
 SVNADMIN="${SVNADMIN:=svnadmin}"
 #SVNADMIN_FLAGS=""
 VCS_ID_KEYWORDS="${VCS_ID_KEYWORDS:=FreeBSD Id MCom}"
@@ -1074,6 +1076,25 @@ run_portshaker_command()
 					fi
 				fi
 				;;
+                        svnlite)
+                                if [ -z "${svn_checkout_path}" ]; then
+                                        err 1 "\$svn_checkout_path is not defined."
+                                fi
+                                if [ ! -d "${_portsdir}/.svn" ]; then
+                                        debug "Running '${SVNLITE} ${SVNLITE_FLAGS} checkout \"${svn_checkout_path}\" \"${_portsdir}\"'."
+                                        ${SVN} ${SVNLITE_FLAGS} checkout "${svn_checkout_path}" "${_portsdir}"
+                                        if [ $? -ne 0 ]; then
+                                                err 1 "Subversion checkout failed."
+                                        fi
+                                else
+                                        cd "${_portsdir}"
+                                        debug "Running '${SVNLITE} ${SVNLITE_FLAGS} update'."
+                                        ${SVNLITE} ${SVNLITE_FLAGS} update
+                                        if [ $? -ne 0 ]; then
+                                                err 1 "Subversion update failed."
+                                        fi
+                                fi
+                                ;;
 			svn+subtrees)
 				if [ -z "${svn_checkout_path}" ]; then
 					err 1 "\$svn_checkout_path is not defined."
